### ISSUE TITLE
update to bootstrap 3.0 and above

### ISSUE THREAD

**Issue by erwinkarim** [erwinkarim/fireworks#12]
Update user interface to bootstrap 3.0

will be a major re-work of the user interface.

since this will be a major re-write, a new branch has been created since commit dec3705468d2e59b8924d5a5a2fb6b92b4f3353f

still some issues corp up and need closure
- [x] #15 chart width in panel
- [x] #16 update license server action
- [x] #17 update report schedule action
- [x] #18 gaps issues when adding new users
